alter table nail_styles
  add column if not exists nail_length text,
  add column if not exists taxonomy jsonb not null default '{}'::jsonb;
create index if not exists idx_nail_styles_taxonomy on nail_styles using gin (taxonomy);

update nail_styles set taxonomy = '{"colors": ["粉色系", "红色系"], "techniques": ["手绘", "花卉", "立体花", "法式", "法式变体", "钻饰", "宝石", "珍珠"], "shapes": ["方圆型", "中长圆方型"], "styles": ["复古", "老钱", "莫兰迪"], "occasions": ["约会", "节日", "新年", "圣诞"], "lengths": ["中长款"]}'::jsonb, tags = array['红色系','裸粉色','中长圆方型','法式','手绘','蝴蝶结','丝带','钻饰','复古','芭蕾风','纯欲','新年','圣诞','约会','粉色系','花卉','立体花','法式变体','宝石','珍珠','方圆型','老钱','莫兰迪','节日','中长款']::text[], occasion = array['约会','节日','新年','圣诞']::text[], color = '粉色系 / 红色系', finish = '手绘', nail_length = 'medium' where id = 'library-20260514-001';
update nail_styles set taxonomy = '{"colors": ["粉色系", "黑色系", "白色系", "灰色系"], "techniques": ["动物纹", "手绘", "花卉", "立体花", "法式", "法式变体", "纯色", "跳色", "几何"], "shapes": ["方圆型", "短方圆型"], "styles": ["复古", "老钱", "莫兰迪", "日系", "清新", "可爱"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['黑白色','透粉色','短方圆型','法式','手绘','奶牛纹','动物纹','跳色','拼接','可爱','复古','日常','粉色系','黑色系','白色系','灰色系','花卉','立体花','法式变体','纯色','几何','方圆型','老钱','莫兰迪','日系','清新','通勤','百搭','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '粉色系 / 黑色系', finish = '动物纹', nail_length = 'natural' where id = 'library-20260514-002';
update nail_styles set taxonomy = '{"colors": ["粉色系", "金属色系", "金银色"], "techniques": ["猫眼", "魔镜", "极光"], "shapes": ["尖型", "尖杏仁型"], "styles": ["欧美", "辣妹", "Y2K"], "occasions": ["派对", "蹦迪", "晚宴"], "lengths": ["长款"]}'::jsonb, tags = array['玫瑰金','金属色系','尖杏仁型','魔镜粉','金属质感','Y2K','辣妹风','欧美风','未来感','个性','派对','粉色系','金银色','猫眼','魔镜','极光','尖型','欧美','辣妹','蹦迪','晚宴','长款']::text[], occasion = array['派对','蹦迪','晚宴']::text[], color = '粉色系 / 金属色系', finish = '猫眼', nail_length = 'long' where id = 'library-20260514-003';
update nail_styles set taxonomy = '{"colors": ["粉色系", "蓝色系", "绿色系", "冷色系"], "techniques": ["亮片", "闪粉", "爆闪", "纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["极简", "冷淡", "INS", "高级感", "轻奢", "气质"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['灰蓝色','粉色系','莫兰迪色','短圆方型','亮片','拼接','跳色','甜酷风','简约','气质','通勤','日常','蓝色系','绿色系','冷色系','闪粉','爆闪','纯色','几何','方圆型','极简','冷淡','INS','高级感','轻奢','百搭','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '粉色系 / 蓝色系', finish = '亮片', nail_length = 'natural' where id = 'library-20260514-004';
update nail_styles set taxonomy = '{"colors": ["彩色", "多色", "粉色系"], "techniques": ["渐变", "腮红", "冰透", "钻饰", "宝石", "珍珠"], "shapes": ["方圆型"], "styles": ["奢华", "巴洛克", "千金", "日系", "清新", "可爱"], "occasions": ["派对", "蹦迪", "晚宴"], "lengths": ["中长款"]}'::jsonb, tags = array['裸粉色','彩色系','中长方形','透底','钻饰','堆钻','爱心','宝石','巴洛克','华丽','奢华','玩具风','派对','彩色','多色','粉色系','渐变','腮红','冰透','珍珠','方圆型','千金','日系','清新','可爱','蹦迪','晚宴','中长款']::text[], occasion = array['派对','蹦迪','晚宴']::text[], color = '彩色 / 多色', finish = '渐变', nail_length = 'medium' where id = 'library-20260514-005';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "黑色系", "白色系", "灰色系"], "techniques": ["渐变", "腮红", "冰透", "钻饰", "宝石", "珍珠"], "shapes": ["尖型"], "styles": ["暗黑", "朋克", "酷感", "欧美", "辣妹", "Y2K"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['黑色系','裸色系','长尖型','透底','五角星','钻饰','暗黑风','哥特风','辣妹风','朋克','酷感','大地色系','白色系','灰色系','渐变','腮红','冰透','宝石','珍珠','尖型','暗黑','欧美','辣妹','Y2K','长款']::text[], occasion = array['日常']::text[], color = '裸色系 / 大地色系', finish = '渐变', nail_length = 'long' where id = 'library-20260514-006';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "金属色系", "金银色", "黑色系", "白色系", "灰色系"], "techniques": ["法式", "法式变体", "渐变", "腮红", "冰透", "钻饰", "宝石", "珍珠"], "shapes": ["梯型"], "styles": ["仙气", "温柔", "梦幻", "奢华", "巴洛克", "千金"], "occasions": ["婚礼", "新娘", "宴会"], "lengths": ["长款"]}'::jsonb, tags = array['白色系','裸色系','银色系','梯形','冰透','渐变','腮红甲','钻饰','锆石','流苏','仙气','奢华','法式','千金风','婚礼','新娘','宴会','大地色系','金属色系','金银色','黑色系','灰色系','法式变体','腮红','宝石','珍珠','梯型','温柔','梦幻','巴洛克','千金','长款']::text[], occasion = array['婚礼','新娘','宴会']::text[], color = '裸色系 / 大地色系', finish = '法式', nail_length = 'long' where id = 'library-20260514-007';
update nail_styles set taxonomy = '{"colors": ["蓝色系", "绿色系", "冷色系", "裸色系", "大地色系"], "techniques": ["纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["日系", "清新", "可爱", "极简", "冷淡", "INS"], "occasions": ["日常", "通勤", "百搭", "秋冬"], "lengths": ["短款"]}'::jsonb, tags = array['绿色系','大地色','奶茶色','短圆方型','纯色','跳色','拼色','日系','极简','INS风','冷淡风','秋冬','日常','通勤','蓝色系','冷色系','裸色系','大地色系','几何','方圆型','清新','可爱','冷淡','INS','百搭','短款']::text[], occasion = array['日常','通勤','百搭','秋冬']::text[], color = '蓝色系 / 绿色系', finish = '纯色', nail_length = 'natural' where id = 'library-20260514-008';
update nail_styles set taxonomy = '{"colors": ["彩色", "多色", "红色系", "蓝色系", "绿色系", "冷色系"], "techniques": ["亮片", "闪粉", "爆闪", "手绘", "花卉", "立体花", "纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["日系", "清新", "可爱"], "occasions": ["日常", "通勤", "百搭", "春夏", "度假", "清凉"], "lengths": ["短款"]}'::jsonb, tags = array['彩色系','酒红色','蓝色系','黄色系','短圆方型','手绘','立体小花','格纹','波点','亮片','跳色','拼色','日系','可爱','活泼','春夏','日常','彩色','多色','红色系','绿色系','冷色系','闪粉','爆闪','花卉','立体花','纯色','几何','方圆型','清新','通勤','百搭','度假','清凉','短款']::text[], occasion = array['日常','通勤','百搭','春夏','度假','清凉']::text[], color = '彩色 / 多色', finish = '亮片', nail_length = 'natural' where id = 'library-20260514-009';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "金属色系", "金银色"], "techniques": ["亮片", "闪粉", "爆闪", "动物纹", "手绘", "花卉", "立体花", "渐变", "腮红", "冰透"], "shapes": ["尖型"], "styles": ["欧美", "辣妹", "Y2K"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['裸色系','银色系','长尖型','渐变','细闪','亮粉','手绘','豹纹','动物纹','轻欧美','辣妹风','个性','高街','大地色系','金属色系','金银色','亮片','闪粉','爆闪','花卉','立体花','腮红','冰透','尖型','欧美','辣妹','Y2K','长款']::text[], occasion = array['日常']::text[], color = '裸色系 / 大地色系', finish = '亮片', nail_length = 'long' where id = 'library-20260514-010';
update nail_styles set taxonomy = '{"colors": ["彩色", "多色", "粉色系", "裸色系", "大地色系"], "techniques": ["亮片", "闪粉", "爆闪", "渐变", "腮红", "冰透", "纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["日系", "清新", "可爱"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['裸色系','粉色系','彩色系','短圆方型','冰透','渐变','腮红甲','波点','亮片','彩色波点','日系','少女心','可爱','清爽','日常','彩色','多色','大地色系','闪粉','爆闪','腮红','纯色','跳色','几何','方圆型','清新','通勤','百搭','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '彩色 / 多色', finish = '亮片', nail_length = 'natural' where id = 'library-20260514-011';
update nail_styles set taxonomy = '{"colors": ["金属色系", "金银色", "黑色系", "白色系", "灰色系"], "techniques": ["亮片", "闪粉", "爆闪", "法式", "法式变体", "钻饰", "宝石", "珍珠"], "shapes": ["尖型"], "styles": ["暗黑", "朋克", "酷感", "欧美", "辣妹", "Y2K", "高级感", "轻奢", "气质"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['黑色系','银色系','灰色系','长尖型','细闪','爆闪','法式','平法式','钻饰','方形钻','冷艳','高级感','轻奢','欧美风','个性','金属色系','金银色','白色系','亮片','闪粉','法式变体','宝石','珍珠','尖型','暗黑','朋克','酷感','欧美','辣妹','Y2K','气质','长款']::text[], occasion = array['日常']::text[], color = '金属色系 / 金银色', finish = '亮片', nail_length = 'long' where id = 'library-20260514-012';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "金属色系", "金银色"], "techniques": ["亮片", "闪粉", "爆闪", "动物纹", "手绘", "花卉", "立体花", "渐变", "腮红", "冰透", "钻饰", "宝石", "珍珠"], "shapes": ["尖型"], "styles": ["奢华", "巴洛克", "千金", "欧美", "辣妹", "Y2K"], "occasions": ["派对", "蹦迪", "晚宴"], "lengths": ["长款"]}'::jsonb, tags = array['裸色系','银色系','长尖型','渐变','细闪','手绘','豹纹','动物纹','钻饰','堆钻','超大异形钻','宝石','奢华','巴洛克','辣妹风','欧美风','派对','大地色系','金属色系','金银色','亮片','闪粉','爆闪','花卉','立体花','腮红','冰透','珍珠','尖型','千金','欧美','辣妹','Y2K','蹦迪','晚宴','长款']::text[], occasion = array['派对','蹦迪','晚宴']::text[], color = '裸色系 / 大地色系', finish = '亮片', nail_length = 'long' where id = 'library-20260514-013';
update nail_styles set taxonomy = '{"colors": ["金属色系", "金银色", "黑色系", "白色系", "灰色系"], "techniques": ["猫眼", "魔镜", "极光", "纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["极简", "冷淡", "INS", "高级感", "轻奢", "气质"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['灰色系','银色系','金属性','短圆方型','纯色','魔镜粉','金属质感','描边','跳色','拼色','极简','高级感','INS风','冷淡风','通勤','日常','金属色系','金银色','黑色系','白色系','猫眼','魔镜','极光','几何','方圆型','冷淡','INS','轻奢','气质','百搭','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '金属色系 / 金银色', finish = '猫眼', nail_length = 'natural' where id = 'library-20260514-014';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "金属色系", "金银色"], "techniques": ["亮片", "闪粉", "爆闪", "渐变", "腮红", "冰透", "钻饰", "宝石", "珍珠"], "shapes": ["尖型"], "styles": ["奢华", "巴洛克", "千金"], "occasions": ["婚礼", "新娘", "宴会", "派对", "蹦迪", "晚宴"], "lengths": ["长款"]}'::jsonb, tags = array['金色系','裸色系','香槟金','长尖型','渐变','细闪','亮粉','钻饰','堆钻','大宝石','水钻','奢华','华丽','千金风','宴会','婚礼','派对','大地色系','金属色系','金银色','亮片','闪粉','爆闪','腮红','冰透','宝石','珍珠','尖型','巴洛克','千金','新娘','蹦迪','晚宴','长款']::text[], occasion = array['婚礼','新娘','宴会','派对','蹦迪','晚宴']::text[], color = '裸色系 / 大地色系', finish = '亮片', nail_length = 'long' where id = 'library-20260514-015';
update nail_styles set taxonomy = '{"colors": ["粉色系", "黑色系", "白色系", "灰色系"], "techniques": ["渐变", "腮红", "冰透", "猫眼", "魔镜", "极光"], "shapes": ["尖型", "尖杏仁型"], "styles": ["仙气", "温柔", "梦幻", "高级感", "轻奢", "气质"], "occasions": ["婚礼", "新娘", "宴会", "日常", "通勤", "百搭", "约会"], "lengths": ["长款"]}'::jsonb, tags = array['白色系','裸粉色','尖杏仁型','冰透','猫眼','宽猫眼','白月光','仙气','温柔','高级感','日常','约会','婚礼','粉色系','黑色系','灰色系','渐变','腮红','魔镜','极光','尖型','梦幻','轻奢','气质','新娘','宴会','通勤','百搭','长款']::text[], occasion = array['婚礼','新娘','宴会','日常','通勤','百搭','约会']::text[], color = '粉色系 / 黑色系', finish = '渐变', nail_length = 'long' where id = 'library-20260514-016';
update nail_styles set taxonomy = '{"colors": ["黑色系", "白色系", "灰色系"], "techniques": ["法式", "法式变体", "纯色", "跳色", "几何"], "shapes": ["尖型", "尖杏仁型"], "styles": ["极简", "冷淡", "INS", "高级感", "轻奢", "气质"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["长款"]}'::jsonb, tags = array['黑白色','尖杏仁型','纯色','法式','斜法式','V形法式','几何','线条','拼色','跳色','极简','高级感','冷淡风','日常','通勤','黑色系','白色系','灰色系','法式变体','尖型','冷淡','INS','轻奢','气质','百搭','长款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '黑色系 / 白色系', finish = '法式', nail_length = 'long' where id = 'library-20260514-017';
update nail_styles set taxonomy = '{"colors": ["粉色系", "裸色系", "大地色系"], "techniques": ["渐变", "腮红", "冰透"], "shapes": ["椭圆型"], "styles": ["仙气", "温柔", "梦幻", "日系", "清新", "可爱"], "occasions": ["婚礼", "新娘", "宴会"], "lengths": ["长款"]}'::jsonb, tags = array['裸色系','粉色系','长椭圆型','腮红晕染','微雕排钻','弧形微笑线','仙女风','日系温柔','婚礼','大地色系','渐变','腮红','冰透','椭圆型','仙气','温柔','梦幻','日系','清新','可爱','新娘','宴会','长款']::text[], occasion = array['婚礼','新娘','宴会']::text[], color = '粉色系 / 裸色系', finish = '渐变', nail_length = 'long' where id = 'library-20260514-018';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系"], "techniques": [], "shapes": ["方圆型", "短方圆型"], "styles": ["复古", "老钱", "莫兰迪", "极简", "冷淡", "INS"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['裸色系','奶白色','短方圆型','极简风','老钱风职场通勤','职场通勤','大地色系','方圆型','复古','老钱','莫兰迪','极简','冷淡','INS','日常','通勤','百搭','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '裸色系 / 大地色系', finish = '亮面', nail_length = 'natural' where id = 'library-20260514-019';
update nail_styles set taxonomy = '{"colors": ["粉色系"], "techniques": ["亮片", "闪粉", "爆闪", "手绘", "花卉", "立体花", "钻饰", "宝石", "珍珠"], "shapes": ["梯型"], "styles": ["仙气", "温柔", "梦幻", "日系", "清新", "可爱"], "occasions": ["婚礼", "新娘", "宴会"], "lengths": ["长款"]}'::jsonb, tags = array['粉色系','透粉色','长梯型','3D立体雕花','银色闪粉','碎钻','仙女风','日系温柔','婚礼','亮片','闪粉','爆闪','手绘','花卉','立体花','钻饰','宝石','珍珠','梯型','仙气','温柔','梦幻','日系','清新','可爱','新娘','宴会','长款']::text[], occasion = array['婚礼','新娘','宴会']::text[], color = '粉色系', finish = '亮片', nail_length = 'long' where id = 'library-20260514-020';
update nail_styles set taxonomy = '{"colors": ["粉色系", "裸色系", "大地色系"], "techniques": ["钻饰", "宝石", "珍珠"], "shapes": ["梯型"], "styles": ["欧美", "辣妹", "Y2K"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['裸粉色','透粉底色','裸粉','银色长梯型四角星芒','微钻','爆闪Y2K','甜酷辣妹','粉色系','裸色系','大地色系','钻饰','宝石','珍珠','梯型','欧美','辣妹','Y2K','长款']::text[], occasion = array['日常']::text[], color = '粉色系 / 裸色系', finish = '钻饰', nail_length = 'long' where id = 'library-20260514-021';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系"], "techniques": ["钻饰", "宝石", "珍珠"], "shapes": ["梯型"], "styles": ["高级感", "轻奢", "气质"], "occasions": ["派对", "蹦迪", "晚宴"], "lengths": ["长款"]}'::jsonb, tags = array['大地色系','摩卡奶茶色','长梯型','重工钻饰','轻奢风','千金辣妹','晚宴','蹦迪','裸色系','钻饰','宝石','珍珠','梯型','高级感','轻奢','气质','派对','长款']::text[], occasion = array['派对','蹦迪','晚宴']::text[], color = '裸色系 / 大地色系', finish = '钻饰', nail_length = 'long' where id = 'library-20260514-022';
update nail_styles set taxonomy = '{"colors": ["裸色系", "大地色系", "黑色系", "白色系", "灰色系"], "techniques": ["钻饰", "宝石", "珍珠"], "shapes": ["梯型"], "styles": ["奢华", "巴洛克", "千金"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['白色系','裸色系','长梯型','弧形排珍珠','重工方钻','豪门千金','新娘婚礼','大地色系','黑色系','灰色系','钻饰','宝石','珍珠','梯型','奢华','巴洛克','千金','长款']::text[], occasion = array['日常']::text[], color = '裸色系 / 大地色系', finish = '钻饰', nail_length = 'long' where id = 'library-20260514-023';
update nail_styles set taxonomy = '{"colors": ["彩色", "多色", "蓝色系", "绿色系", "冷色系"], "techniques": ["法式", "法式变体", "纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["仙气", "温柔", "梦幻"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['蓝色系','彩色系','短圆方型','梦幻','光泽感','日常','百搭','法式撞色','金箔琥珀','艺术跳色','静谧蓝','彩色','多色','绿色系','冷色系','法式','法式变体','纯色','跳色','几何','方圆型','仙气','温柔','通勤','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '彩色 / 多色', finish = '法式', nail_length = 'natural' where id = 'library-20260514-024';
update nail_styles set taxonomy = '{"colors": ["彩色", "多色", "蓝色系", "绿色系", "冷色系", "黑色系", "白色系", "灰色系"], "techniques": ["手绘", "花卉", "立体花"], "shapes": [], "styles": ["仙气", "温柔", "梦幻"], "occasions": ["春夏", "度假", "清凉"], "lengths": []}'::jsonb, tags = array['彩色系','蓝色系','白色系','长椭圆','梦幻','仙气','光泽感','度假风','薄荷绿','鸡蛋花','夏日清凉','立体配饰','彩色','多色','绿色系','冷色系','黑色系','灰色系','手绘','花卉','立体花','温柔','春夏','度假','清凉']::text[], occasion = array['春夏','度假','清凉']::text[], color = '彩色 / 多色', finish = '手绘', nail_length = 'medium' where id = 'library-20260514-025';
update nail_styles set taxonomy = '{"colors": ["粉色系", "红色系"], "techniques": ["亮片", "闪粉", "爆闪", "法式", "法式变体"], "shapes": ["梯型"], "styles": ["仙气", "温柔", "梦幻"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["长款"]}'::jsonb, tags = array['粉色系','长梯型','光泽感','日常','梦幻','反向法式','平法式留白','爆闪碎钻胶','玫瑰豆沙红','红色系','亮片','闪粉','爆闪','法式','法式变体','梯型','仙气','温柔','通勤','百搭','长款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '粉色系 / 红色系', finish = '亮片', nail_length = 'long' where id = 'library-20260514-026';
update nail_styles set taxonomy = '{"colors": ["粉色系", "金属色系", "金银色"], "techniques": ["渐变", "腮红", "冰透", "猫眼", "魔镜", "极光"], "shapes": ["方圆型"], "styles": ["仙气", "温柔", "梦幻", "高级感", "轻奢", "气质"], "occasions": ["日常", "通勤", "百搭"], "lengths": ["短款"]}'::jsonb, tags = array['粉色系','金色系','短方圆','光泽感','梦幻','仙气','日常','百搭','极光粉','微闪渐变','温柔风','果冻质感','低调奢华','金属色系','金银色','渐变','腮红','冰透','猫眼','魔镜','极光','方圆型','温柔','高级感','轻奢','气质','通勤','短款']::text[], occasion = array['日常','通勤','百搭']::text[], color = '粉色系 / 金属色系', finish = '渐变', nail_length = 'natural' where id = 'library-20260514-027';
update nail_styles set taxonomy = '{"colors": ["粉色系", "裸色系", "大地色系"], "techniques": [], "shapes": ["杏仁型"], "styles": ["欧美", "辣妹", "Y2K"], "occasions": [], "lengths": ["长款"]}'::jsonb, tags = array['裸色系','粉色系','长杏仁型','纯色冰透','欧美纯欲','伪素颜','大地色系','杏仁型','欧美','辣妹','Y2K','长款']::text[], occasion = array['日常']::text[], color = '粉色系 / 裸色系', finish = '亮面', nail_length = 'long' where id = 'library-20260514-028';
update nail_styles set taxonomy = '{"colors": ["黑色系", "白色系", "灰色系"], "techniques": ["猫眼", "魔镜", "极光"], "shapes": ["方圆型", "短方圆型"], "styles": ["复古", "老钱", "莫兰迪", "极简", "冷淡", "INS"], "occasions": [], "lengths": ["短款"]}'::jsonb, tags = array['白色系','纯色系','短方圆型','纯色镜面','极简','Quiet Luxury','黑色系','灰色系','猫眼','魔镜','极光','方圆型','复古','老钱','莫兰迪','冷淡','INS','短款']::text[], occasion = array['日常']::text[], color = '黑色系 / 白色系', finish = '猫眼', nail_length = 'natural' where id = 'library-20260514-029';
update nail_styles set taxonomy = '{"colors": ["蓝色系", "绿色系", "冷色系", "裸色系", "大地色系"], "techniques": ["纯色", "跳色", "几何"], "shapes": ["方圆型"], "styles": ["复古", "老钱", "莫兰迪"], "occasions": [], "lengths": ["中长款"]}'::jsonb, tags = array['芥末绿','燕麦','奶白','中长方圆','三色复古跳色','莫兰迪','简约复古','蓝色系','绿色系','冷色系','裸色系','大地色系','纯色','跳色','几何','方圆型','复古','老钱','中长款']::text[], occasion = array['日常']::text[], color = '蓝色系 / 绿色系', finish = '纯色', nail_length = 'medium' where id = 'library-20260514-030';
